name: Build Web App
on: 
    push: 
        branches: [ master ]
    pull_request: 
        branches: [ master ]
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Build Web App
      run: msbuild WebNetFramework35.sln 
